volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ../data/wordpress
      o: bind
      type: none
  prometheus_data: {}
  traefik:
    name: traefik
    driver: local
    driver_opts:
      device: ../traefik/certs
      o: bind
      type: none

networks:
  app:
  monitoring:

secrets:
  grafana_username:
    environment: GRAFANA_USERNAME
  grafana_password:
    environment: GRAFANA_PASSWORD

services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"

      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8082"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/etc/traefik
    networks:
      - app
      - monitoring
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"

  nginx:
    build: ./requirements/nginx
    image: nginx:custom
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    depends_on:
      wordpress:
        condition: service_healthy

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
    container_name: cloudsql-proxy
    command:
      - "--port=3306"
      - "firm-region-406414:us-central1:cloud1-db"
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:custom
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_N: ${WP_ADMIN_N}
      WP_ADMIN_P: ${WP_ADMIN_P}
      WP_ADMIN_E: ${WP_ADMIN_E}
      WP_U_NAME: ${WP_U_NAME}
      WP_U_EMAIL: ${WP_U_EMAIL}
      WP_U_PASS: ${WP_U_PASS}
    depends_on:
      - cloudsql-proxy
    networks:
      - app
    network_mode: "service:cloudsql-proxy"
    restart: always
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/wordpress/wp-login.php"]
      interval: 10s
      retries: 10
      start_period: 3m

  redis:
    image: redis:alpine
    container_name: redis-cache
    command: ["redis-server", "--protected-mode", "no", "--maxmemory", "2mb", "--maxmemory-policy", "allkeys-lru"]
    depends_on:
      - nginx
    networks:
      - app
    restart: always

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - dev/disk/:/dev/disk
    privileged: true
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    privileged: true
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    secrets:
      - grafana_username
      - grafana_password
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=2d"
      - "--storage.tsdb.wal-compression"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - monitoring
