volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ../data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ../data/wordpress
      o: bind
      type: none
  prometheus_data: {}
  traefik:
    name: traefik
    driver: local
    driver_opts:
      device: ../traefik/certs
      o: bind
      type: none

networks:
  app:
  monitoring:

secrets:
  grafana_username:
    environment: GRAFANA_USERNAME
  grafana_password:
    environment: GRAFANA_PASSWORD

services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"

      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.metrics.address=:8082"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/etc/traefik
    networks:
      - app
      - monitoring
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"

  nginx:
    build: ./requirements/nginx
    image: nginx:custom
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:custom
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    #   - ./requirements/wordpress/wp_config.sh:/usr/local/bin/wp_config.sh
    # command: ["sh", "-c", "chmod +x /usr/local/bin/wp_config.sh && /usr/local/bin/wp_config.sh"]
    environment:
      MYSQL_DB: ${MDB_DB}
      MYSQL_USER: ${MDB_USER}
      MYSQL_PASSWORD: ${MDB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_N: ${WP_ADMIN_N}
      WP_ADMIN_P: ${WP_ADMIN_P}
      WP_ADMIN_E: ${WP_ADMIN_E}
      WP_U_NAME: ${WP_U_NAME}
      WP_U_EMAIL: ${WP_U_EMAIL}
      WP_U_PASS: ${WP_U_PASS}
    networks:
      - app
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/wordpress/wp-login.php"]
      interval: 10s
      retries: 10
      start_period: 3m

  mariadb:
    image: mariadb
    container_name: mariadb
    command: --innodb-buffer-pool-size=64M --max-connections=50 --key-buffer-size=16M
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MDB_DB}
      MARIADB_USER: ${MDB_USER}
      MARIADB_PASSWORD: ${MDB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MDB_ROOT_PASSWORD}
    networks:
      - app
    restart: on-failure:1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 2m
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis-cache
    command: ["redis-server", "--protected-mode", "no", "--maxmemory", "2mb", "--maxmemory-policy", "allkeys-lru"]
    depends_on:
      - nginx
    networks:
      - app
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - app
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.docker.network=monitoring"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - dev/disk/:/dev/disk
    privileged: true
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    privileged: true
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    secrets:
      - grafana_username
      - grafana_password
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=2d"
      - "--storage.tsdb.wal-compression"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - monitoring
