[servers]
# Adresse IP à attribuer à notre machine virtualbox
# 192.168.56.10

# Adresse IP de notre machine google cloud
wordpress-prod-uc1-ip ansible_host=104.154.171.67

[servers:vars]
ansible_user=perso
ansible_ssh_private_key_file=~/.ssh/gcp_key