[servers]
wordpress-prod-0 ansible_host=34.135.170.44
wordpress-prod-1 ansible_host=35.254.110.73

[servers:vars]
ansible_user=deploy
ansible_ssh_private_key_file=~/.ssh/gcp_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'