- hosts: servers
  remote_user: deploy
  become: true

  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Check necessary dependencies
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Add Docker repository
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_distribution_release }}"
        components: stable
        architectures: amd64
        signed_by: https://download.docker.com/linux/debian/gpg

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Create data directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
      loop:
        - /home/{{ ansible_user }}/data/wordpress
        - /home/{{ ansible_user }}/data/mariadb

    - name: Copy project files to VM
      copy:
        src: ./srcs/
        dest: /home/{{ ansible_user }}/srcs/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create .env file
      copy:
        dest: /home/{{ ansible_user }}/srcs/.env
        content: |
          DOMAIN_NAME={{ ansible_host }}
          {{ lookup('env', 'ENV_FILE') }}

    - name: Create Traefik certs directory
      file:
        path: /home/{{ ansible_user }}/traefik/certs
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Create Traefik acme.json file
      file:
        path: /home/{{ ansible_user }}/traefik/certs/acme.json
        state: touch
        owner: "{{ ansible_user }}"
        mode: '0600'

    - name: Build and launch containers
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/srcs/
        state: present
        build: policy

    - name: Install ufw
      apt:
        name: ufw
        state: latest

    - name: Disable all incoming traffic
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - community.general.ufw:
        rule: allow
        port: ssh
        proto: tcp

    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp
