- hosts: servers
  remote_user: deploy
  become: true

  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: true
        upgrade: dist

    - name: Check necessary dependencies
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create Docker GPG keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/debian
          {{ ansible_facts["distribution_release"] }} stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Create data directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
      loop:
        - /home/{{ ansible_user }}/data/wordpress
        - /home/{{ ansible_user }}/data/mariadb

    - name: Copy project files to VM
      copy:
        src: ./srcs/
        dest: /home/{{ ansible_user }}/srcs/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Add DOMAIN_NAME to .env file
      lineinfile:
        path: /home/{{ ansible_user }}/srcs/.env
        line: "DOMAIN_NAME={{ ansible_host }}"
        state: present
    
    - name: Add Grafana credentials to .env
      lineinfile:
        path: /home/{{ ansible_user }}/srcs/.env
        line: "{{ item }}"
      loop:
        - "GRAFANA_USERNAME={{ lookup('env', 'GRAFANA_USERNAME') }}"
        - "GRAFANA_PASSWORD={{ lookup('env', 'GRAFANA_PASSWORD') }}"

    - name: Build and launch containers
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/srcs/
        state: present
        build: always

    - name: Install ufw
      apt:
        name: ufw
        state: latest

    - name: Disable all incoming traffic
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - community.general.ufw:
        rule: allow
        port: ssh
        proto: tcp

    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp
