name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # ← permet le déclenchement manuel depuis GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_GCP_KEY }}" > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Setup Ansible
        run: |
          python3 -m venv .venv
          .venv/bin/pip install ansible-core
          .venv/bin/ansible-galaxy collection install community.general
          .venv/bin/ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        run: |
          .venv/bin/ansible-playbook -i inventory.ini playbook.yml
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
