name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # ← permet le déclenchement manuel depuis GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_GCP_KEY }}" > ~/.ssh/gcp_key
          chmod 600 ~/.ssh/gcp_key

      - name: Setup Ansible
        run: |
          python3 -m venv .venv
          .venv/bin/pip install ansible-core
          .venv/bin/ansible-galaxy collection install community.general
          .venv/bin/ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        run: |
          .venv/bin/ansible-playbook -i inventory.ini playbook.yml
        env:
          MDB_DB: ${{ vars.MDB_DB }}
          MDB_USER: ${{ vars.MDB_USER }}
          MDB_PASSWORD: ${{ secrets.MDB_PASSWORD }}
          MDB_ROOT_PASSWORD: ${{ secrets.MDB_ROOT_PASSWORD }}
          WP_ADMIN_N: ${{ vars.WP_ADMIN_N }}
          WP_ADMIN_P: ${{ secrets.WP_ADMIN_P }}
          WP_ADMIN_E: ${{ vars.WP_ADMIN_E }}
          WP_U_NAME: ${{ vars.WP_U_NAME }}
          WP_U_EMAIL: ${{ vars.WP_U_EMAIL }}
          WP_U_PASS: ${{ secrets.WP_U_PASS }}
          GRAFANA_USERNAME: ${{ vars.GRAFANA_USERNAME }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
