name: Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "apply ou destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4

      - run: terraform init

      - run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_GCP_KEY_PUB }}

      - name: Terraform Apply or Destroy
        run: terraform ${{ github.event.inputs.action }} -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_GCP_KEY_PUB }}
